#pragma once

#define TRAYSYMBOLS_VERSION_MAJOR 0
#define TRAYSYMBOLS_VERSION_MINOR 2
#define TRAYSYMBOLS_VERSION_PATCH 0
#define TRAYSYMBOLS_VERSION_BUILD 0

#define TRAYSYMBOLS_VERSION_TEXT "0.2.0"
#define TRAYSYMBOLS_FILE_VERSION_TEXT "0.2.0.0"

#define TRAYSYMBOLS_VERSION_TEXT_W L"0.2.0"
#define TRAYSYMBOLS_FILE_VERSION_TEXT_W L"0.2.0.0"
